### ISSUE TITLE
New client translate

### ISSUE THREAD

**Issue by timchez** [thomas-barthelemy/QQ-LoL-Localizer#16]
Title says it all. Are you going to translate the new client for china?

**Comment by Camineet** [comment]
updated client is here today. can't play. 

heeeeeeeeeelp!!!

**Comment by Camineet** [comment]
seriously, it would be one thing if we just lost our english but had same layout.

but layout is completely overhauled, and there's no way to get anything done without the ability to read chinese.  Thomas, we'd really appreciate it you could work on an update if you can possibly make the time for it

**Comment by Camineet** [comment]
Hi guys,

Some good news. My Chinese wife helped me navigate the basics of the new client. I made a custom game just to see if the language remained as English in-game and it does. So, it's just the client that we have to deal with in Chinese which makes things pretty difficult for updating runes but masteries are kind of easy because you can rely on the tooltips and layouts in mobafire to know what you're doing.

i have no idea how we're going to deal with runes because all the descriptions and tooltips are in chinese.  that's a problem.

buying champs is pretty straightforward i think but haven't tried.

anyway, i seems like the sky has not in fact fallen :D

**Comment by thomas-barthelemy** [comment]
Hey there, I'll have a look over the weekend see if anything is possible. good to know it's only an Air client change. Depending on what is done there is a chance nothing is possible and it's too far forked from the original LoL US client.

**Comment by thomas-barthelemy** [comment]
@timchez @Camineet I updated my client and the air-client (for the runes and all) was still in English. Is there a whole different client now?

**Comment by nofacenoname** [comment]
Hello! I am running a fresh install that I just downloaded. 

I can get the client into English for the runs, champs etc. 

However, I get a bug splat if I fix the game files. It seems the font files are no long .txt, they are now .gfx. Please find the attached screenshots. 

![capture](https://cloud.githubusercontent.com/assets/28862249/26305174/d337186c-3f20-11e7-9ebc-d2db8e19f54c.PNG)
![capture2](https://cloud.githubusercontent.com/assets/28862249/26305175/d33b7290-3f20-11e7-90f5-142019b71ed1.PNG)

**Comment by thomas-barthelemy** [comment]
@nofacenoname You should update your QQ Localizer version: https://github.com/thomas-barthelemy/QQ-LoL-Localizer/releases/tag/v2.14

Had a try with latest LoL and it works as expected.

**Comment by nofacenoname** [comment]
@thomas-barthelemy You are 100% correct! I don't know how, but I must have downloaded and older version. 

Thank you for your awesome work and patience!

**Comment by Camineet** [comment]
no luck here. ran as administrator of course. still chinese (attached)
![capture](https://cloud.githubusercontent.com/assets/10620070/26353287/47377f00-3ff2-11e7-8ee9-ff0f8c83ce8a.PNG)

**Comment by Camineet** [comment]
and yes, the game client was closed when i ran the localizer

**Comment by timchez** [comment]
Fixed with last localizer and the client still is in chinese. Thomas, how does it work with you?
![1](https://cloud.githubusercontent.com/assets/20891077/26363324/41c57ba0-4013-11e7-9693-dc97cec9f580.jpg)
![2](https://cloud.githubusercontent.com/assets/20891077/26363325/41c6cec4-4013-11e7-88f6-8f0938d1abd0.jpg)

e

**Comment by nofacenoname** [comment]
Hello again, 
Fresh install on a separate computer, and the client is still in Chinese. 
![capture](https://cloud.githubusercontent.com/assets/28862249/26389905/c473fee8-408e-11e7-9f0c-0d30d78e4003.JPG)

**Comment by nofacenoname** [comment]
Hi, I received a 1 day suspension because I kept bug splatting trying on the above account. After login in and then selecting a server, this opened. I thought it might be interesting/ useful. :-) 


![strange screen - region](https://cloud.githubusercontent.com/assets/28862249/26398698/d521dd6e-40ac-11e7-858e-37a3aa514033.jpg)


![strange screen - language](https://cloud.githubusercontent.com/assets/28862249/26398710/e118e14e-40ac-11e7-8a95-1215288c4682.jpg)

**Comment by nofacenoname** [comment]
Hello again, My account got a 1 day ban after bugsplatting for too many games. (should have tested on a custom...) Now after logging in and choosing a server I am taken to this screen. 

I messed up taking the screen shot, but there is an option to choose language and it has "English" or ''中文“  I thought it might be interesting/ useful. 

![strange screen - region](https://cloud.githubusercontent.com/assets/28862249/26399291/025aef08-40af-11e7-9185-6f007c90633e.jpg)

**Comment by Sancty333** [comment]
same issue here the client is back in chinese impossible to turn it in english anymore but localizer says fixed...the problem will be in 2 weeks since they will change runes and masteries .... If I cannot read it anymore I can say goodbye to ranked games ... T.T

**Comment by truckbus** [comment]
just my two cents:  localizer is is giving the all green, however my client is all chinese. prior to the this patch I just changed the locale.properties and it was all in english. no need for localizer.

since new patch nothing has been working. 
screens:
https://gyazo.com/d82a69a8f22e14d99e3e3918a0991d48

https://gyazo.com/76c07149eb3a41917670567393dfbc1d 

thanks heaps for your help so far Thomas. i'll keep checking for any progress.

**Comment by leviper** [comment]
Hi Thomas, Thanks for your awesome tool, I think the old client has been ruled out, from this week i can only use the new client and would be nice if we could get a tool same like your previous one, its still not too bad as in game is in English, but still would be nice to see the client in English to see all the stats and stuff. Thanks in advance.

**Comment by truckbus** [comment]
@Sancty333 mate I only ever had it fixed prior to this current patch.

with the new client i've had no luck.

**Comment by leviper** [comment]
Hi Everyone, I found an easy fix to change the new LOL Client to English. 

Go to "英雄联盟\LeagueClient\Config\LeagueClientSettings.yaml" and change zh_CN to en_US or any language you want the client to be for example i think french is fr_FR, German should be de_DE. 

For in game use Thomas's Localizer to change to English.

Happy Gaming 🗡  

If you guys are playing in my server, please add my ID: ragegod
![me](https://cloud.githubusercontent.com/assets/17830938/26753626/dd7fc01e-489c-11e7-89dd-be1653633d9b.png)

**Comment by truckbus** [comment]
@leviper mate you're a legend. works a charm.

**Comment by thomas-barthelemy** [comment]
Thanks everybody for chipping in, finally got to have a try with the new pre-game client and updating the localizer accordingly.

See https://github.com/thomas-barthelemy/QQ-LoL-Localizer/releases/tag/v2.15

**Comment by Camineet** [comment]
fabulous xD thank you all

**Comment by Sancty333** [comment]
Thomas you're a god haha
